version: '2'
services:
    nginx:
        container_name: nginx
        build: ./docker/nginx/
        ports:
            - 80:80
        links:
            - php
        restart: always
        volumes_from:
            - app
    php:
        build: ./docker/php-fpm/
        container_name: php
        expose:
            - 9000
        links:
            - db
            - mailhog
        restart: always
        volumes_from:
            - app
    app:
        image: php:7.0-fpm
        container_name: app
        volumes:
            - .:/var/www/html:Z
        command: "true"
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: game
            MYSQL_USER: game
            MYSQL_PASSWORD: 123
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"
            - "1025"
volumes:
  db-data:
  app:
