version: '2'
services:
    nginx:
        container_name: nginx
        build: ./docker/nginx/
        ports:
            - 80:80
        links:
            - php
        restart: always
        volumes_from:
            - app
    php:
        build: ./docker/php-fpm/
        container_name: php
        expose:
            - 9000
        links:
            - db
            - db-test
        restart: always
        volumes_from:
            - app
    app:
        image: php:7.0-fpm
        container_name: app
        volumes:
            - .:/var/www/html:Z
        command: "true"
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        expose:
            - 3306
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: game
            MYSQL_USER: game
            MYSQL_PASSWORD: 123
    db-test:
        image: mysql:latest
        ports:
            - 3307:3306
        expose:
            - 3307
        container_name: db-test
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: game_test
            MYSQL_USER: game_test
            MYSQL_PASSWORD: 123
volumes:
  app:
