# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.hero_factory:
        class:     AppBundle\Utils\HeroFactory
        arguments: ['@doctrine.orm.entity_manager', '@validator']

    app.command.my_command:
            class: AppBundle\Command\CreateHeroCommand
            arguments: ["@doctrine.orm.entity_manager", "@app.hero_factory"]
            tags:
                - { name: console.command }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
