# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.command.create_hero:
            class: AppBundle\Command\CreateHeroCommand
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: console.command }

    app.command.start_game:
                class: AppBundle\Command\StartGameCommand
                arguments: ["@doctrine.orm.entity_manager"]
                tags:
                    - { name: console.command }
    app.command.hero_stats:
                class: AppBundle\Command\HeroStatsCommand
                arguments: ["@doctrine.orm.entity_manager"]
                tags:
                    - { name: console.command }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
